version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api-server
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env.stag
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - limsm-net
    ports:
      - '3000:3000'
  # docker-compose exec mysql bash
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-server
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: nestProject
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    networks:
      - limsm-net
    # volumes:
    #   - mysql:/var/lib/mysql
volumes:
  mysql:
networks:
  limsm-net:
