service: nest-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  profile: default
  region: ap-northeast-2

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: nest-project
