// REPOSITORY TOKEN
export const USER_CREATE_REPOSITORY_TOKEN =
  'USER_CREATE_REPOSITORY_TOKEN' as const;
export const USER_DELETE_REPOSITORY_TOKEN =
  'USER_DELETE_REPOSITORY_TOKEN' as const;
export const USER_EXIST_REPOSITORY_TOKEN =
  'USER_EXIST_REPOSITORY_TOKEN' as const;
export const USER_FIND_REPOSITORY_TOKEN = 'USER_FIND_REPOSITORY_TOKEN' as const;
export const USER_UPDATE_REPOSITORY_TOKEN =
  'USER_UPDATE_REPOSITORY_TOKEN' as const;
