// service
export const AUTH_SIGNUP_SERVICE_TOKEN = 'AUTH_SIGNUP_SERVICE_TOKEN' as const;
export const AUTH_LOGIN_SERVICE_TOKEN = 'AUTH_LOGIN_SERVICE_TOKEN' as const;

// repository
export const JWT_TOKEN_REPOSITORY_TOKEN = 'JWT_TOKEN_REPOSITORY_TOKEN' as const;
